data = ['あ', 'い', 'う', 'え', 'お', 'か', 'き', 'く', 'け', 'こ']
print(data[2:5])
print(data[2:])
print(data[:5])
print(data[:])
print(data[-7:])
print(data[-7:-5])
print(data[::2])
print(data[1::2])
print(data[::-1])
