print('abc123'.isalnum())
print('abc++'.isalnum())
print('abcde'.isalpha())
print('abc123'.isalpha())
print('abc'.isascii())
print('あいう'.isascii())
print('100'.isdecimal())
print('0x64'.isdecimal())
print('1234'.isdigit())
print('1234.56'.isdigit())
print('百万'.isnumeric())
print('million'.isnumeric())
print('abc_123'.isidentifier())
print('abc-123'.isidentifier())
print('wings'.islower())
print('Wings'.islower())
print('WINGS'.isupper())
print('Wings'.isupper())
print('Wings Project'.istitle())
print('WINGS Project'.istitle())
print('Hello World'.isprintable())
print('Hello\nWorld'.isprintable())
print('   '.isspace())
print('***'.isspace())
